---
title: ''
geometry: "left=2cm,right=2cm,top=2cm,bottom=2cm"
output:
  pdf_document: default
  html_document: default
editor_options:
  markdown:
    wrap: 100
---

```{r setup, message=FALSE, echo=TRUE, include=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# MA256 Lesson 3 - Significance - Strength of Evidence (1.1-1.2)

### Defintions review

\textbf{Statistical Significance}


\vfill

\textbf{What is the 3S Strategy?}


\vfill

What is the difference between a \textbf{parameter} and a \textbf{statistic}?


\vfill

\textbf{Define:}

\hspace{.1in}

\textbf{$H_0$} :

\vfill 

\hspace{.1in} \textbf{$H_a$} :
\vfill 

\hspace{.1in} \textbf{$\pi$} :
\vfill 

\hspace{.1in} \textbf{$\hat{p}$} :
\vfill 

\hspace{.1in} \textbf{n} :
\vfill 

\hspace{.1in} \textbf{p-value} :

\vfill \textbf{Classify the strength of evidence for each range of p-values.}

```{=tex}
\begin{tabular}{cccc|c}
\vspace{.1in}
0.1 & $< p$ & & & \\ 
\vspace{.1in}
0.05 & $< p \le$& 0.1& & \\
\vspace{.1in}
0.01 & $< p \le$ & 0.05 & &  \\
\vspace{.1in}
& $ p \le$ & 0.01 & & 
\end{tabular}
```
\vfill

\newpage

## Chips Ahoy vs Keebler Original Chocolate Chip Cookies

Chips Ahoy! conducted a blind taste-test experiment with 50 randomly selected consumers and recorded
whether they preferred Chips Ahoy! over Keebler's original chocolate chip cookies. Of those 50
consumers, 45 (90%) of them preferred Chips Ahoy! Chips Ahoy! now claims that 90% of consumers
prefer their cookies over Keebler's.

**Step 1: Ask a Research Question:** Q1) Restate from the given information.


\vfill

**Step 2: Design a Study & Collect Data:** Q3) Explain what type of study was conducted.


\vfill

**Step 3: Explore the Data:** Q4) What could we do with the data to help us understand it better?


\vfill

**Step 4:** Draw Inferences: Significance (today's lesson!)

*To draw inferences for this or any other research question, we must set the framework by answering
the following questions. Do this at boards in teams of 2-3:*

Q5) What are the observational units?

\vfill

Q6) What is the sample size and number of samples?

\vfill

Q7) Identify & classify the variable collected.


\vfill

\newpage


Q8) What is the symbol, definition & value of the sample statistic?


\vfill

Q9) What is the symbol, definition, & value of the population parameter?


\vfill



Q10) What are the null \& alternate hypotheses in words and symbol notation?

\vfill




Q11) With the framework established, we can use the 3S strategy and *One Proportion* applet
(<http://www.isi-stats.com/isi2nd/ISIapplets2021.html>) to estimate the likelihood that Chips Ahoy
got the result they did if consumers could not taste a difference and were randomly choosing one of
the two cookies. 

**1. Statistic:** Write out the statistic: $\hat{p} = 45 / 50 = 90\% \; or \; 0.9$

**2. Simulate:** Run the simulation using the *One Proportion* applet. 

*Getting the Null Distribution:*

\hspace{0.5cm} Probability of choosing Chips Ahoy! (success/heads) = $\pi$ (Parameter) = 

\hspace{0.5cm} Number of tosses = n (Sample size) = 

\hspace{0.5cm} Number of repetitions = 1,000

\hspace{0.5cm} Select "Draw Samples" button. 

**3. Strength of Evidence: ** Q12) How common/uncommon is our observation? Report the p-value. Select the “Count samples” “Count” button to calculate the P-value for this simulation. (What number should you use for the *As extreme as* value?) Did we prove the alternative hypothesis? 



\vfill

 
\newpage 

**Step 4: Draw Inferences:  ** Q13) What can you conclude from this study?

\vfill

**Step 5: Formulate Conclusions: ** Q14) Can you generalize to other brands? Can you identify any bias in the study? 
  

\vfill

**Step 6: Look Back and Ahead:**  Q15) Identify limitations & suggest ways to overcome in new studies. 


\vfill

### A third competitor. 

Q16) How would the analysis above change if we introduced a third cookie competitor and conducted the experiment in our classroom? 

\vfill

Q17)Is it possible for the observed proportion to match the null hypothesis if the null hypothesis is false?

\vfill

Q18) Is it possible for the observed proportion to differ significantly from the null hypothesis if the null is true?


\vfill



